# Generated by Django 5.0.6 on 2024-06-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('bod_id', models.AutoField(primary_key=True, serialize=False)),
                ('bod_nombre', models.CharField(max_length=30)),
                ('bod_ubicacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBodega',
            fields=[
                ('det_bod_id', models.AutoField(primary_key=True, serialize=False)),
                ('det_bod_cantidad', models.PositiveIntegerField()),
                ('det_bod_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articulo')),
                ('det_bod_bod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bodega')),
            ],
        ),
    ]
