# Generated by Django 5.0.6 on 2024-06-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articulo_art_eliminado_bodega_bod_eliminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallebodega',
            name='det_bod_art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.articulo'),
        ),
        migrations.AlterField(
            model_name='detallebodega',
            name='det_bod_bod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bodega'),
        ),
    ]
